# Generated by Django 4.1.1 on 2022-09-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numTelefono', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
    ]
