# Generated by Django 4.1.1 on 2022-09-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numTelefono', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateTimeField(max_length=50)),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
