# Generated by Django 4.1.1 on 2022-09-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospiApp', '0005_familiardesignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiardesignado',
            name='correo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='familiardesignado',
            name='parentesco',
            field=models.CharField(default='', max_length=20),
        ),
    ]
