# Generated by Django 4.1.1 on 2022-09-14 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospiApp', '0006_familiardesignado_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignoVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oximetria', models.FloatField()),
                ('frecuenciaRespiratoria', models.FloatField()),
                ('frecuenciaCardiaca', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('presionArterial', models.FloatField()),
                ('glicemia', models.FloatField()),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospiApp.paciente')),
            ],
        ),
    ]
