from .pacienteSerializer import PacienteSerializer
from .medicoSerializer import MedicoSerializer
from .pacienteCambiarMedicoSerializer import PacienteCambiarMedicoSerializer
from .familiarDesignadoSerializer import FamiliarDesignadoSerializer
from .signoVitalSerializer import SignoVitalSerializer

